# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ninckblokje
email: changjnb at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Just a small blog about software I write, primarily focussed
  on Oracle Service Bus, Oracle SOA Suite and Oracle WebLogic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ninckblokje.github.io" # the base hostname & protocol for your site
twitter_username: ninckblokje
github_username:  ninckblokje

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
